# Generated by Django 3.1.7 on 2021-03-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geradorPdf', '0003_profile_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.CharField(default='ss', max_length=200, verbose_name='degree'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='www', max_length=100, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='qqqqqqqqqq', max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='previous_work',
            field=models.TextField(default='rrrrrrrrrr', max_length=1000, verbose_name='previous_work'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(default='ffffffffffff', max_length=1000, verbose_name='skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sumary',
            field=models.TextField(default='asdfasdf', max_length=500, verbose_name='sumary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(default=1, max_length=100, verbose_name='university'),
            preserve_default=False,
        ),
    ]
