# Generated by Django 3.1.7 on 2021-03-08 14:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('geradorPdf', '0004_auto_20210308_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='teste',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='3135324085', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
