# Generated by Django 3.1.7 on 2021-03-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geradorPdf', '0005_auto_20210308_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
