# Generated by Django 3.1.7 on 2021-03-08 14:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('geradorPdf', '0006_remove_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='35324085', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
