# Generated by Django 3.1.7 on 2021-03-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geradorPdf', '0007_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
