# Generated by Django 3.1.7 on 2021-03-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geradorPdf', '0008_auto_20210308_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
